- resultado:
    accuracy: 97.57
    df:
    - Pérdida: 0.0474
      Época: 1
    - Pérdida: 0.059
      Época: 2
    - Pérdida: 0.1304
      Época: 3
    - Pérdida: 0.0178
      Época: 4
    - Pérdida: 0.0933
      Época: 5
    - Pérdida: 0.2327
      Época: 6
    - Pérdida: 0.2053
      Época: 7
    - Pérdida: 0.0375
      Época: 8
    - Pérdida: 0.0512
      Época: 9
    - Pérdida: 0.0664
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: ReLU
      capas_ocultas:
      - 784
      - 512
      - 256
    performance: 2.6940093
  timestamp: 24-12-20_994410
- resultado:
    accuracy: 97.28
    df:
    - Pérdida: 0.2591
      Época: 1
    - Pérdida: 0.1996
      Época: 2
    - Pérdida: 0.1494
      Época: 3
    - Pérdida: 0.0459
      Época: 4
    - Pérdida: 0.0142
      Época: 5
    - Pérdida: 0.197
      Época: 6
    - Pérdida: 0.0528
      Época: 7
    - Pérdida: 0.1229
      Época: 8
    - Pérdida: 0.1646
      Época: 9
    - Pérdida: 0.0117
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: ReLU
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.6776457166666665
  timestamp: 24-12-20_911315
- resultado:
    accuracy: 97.81
    df:
    - Pérdida: 0.0724
      Época: 1
    - Pérdida: 0.1238
      Época: 2
    - Pérdida: 0.0503
      Época: 3
    - Pérdida: 0.0089
      Época: 4
    - Pérdida: 0.1991
      Época: 5
    - Pérdida: 0.1802
      Época: 6
    - Pérdida: 0.0069
      Época: 7
    - Pérdida: 0.0602
      Época: 8
    - Pérdida: 0.0171
      Época: 9
    - Pérdida: 0.0157
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: ReLU
      capas_ocultas:
      - 784
      - 392
    performance: 2.539843916666667
  timestamp: 24-12-20_543576
- resultado:
    accuracy: 97.47
    df:
    - Pérdida: 0.4029
      Época: 1
    - Pérdida: 0.14
      Época: 2
    - Pérdida: 0.0741
      Época: 3
    - Pérdida: 0.0594
      Época: 4
    - Pérdida: 0.0329
      Época: 5
    - Pérdida: 0.0459
      Época: 6
    - Pérdida: 0.0492
      Época: 7
    - Pérdida: 0.183
      Época: 8
    - Pérdida: 0.1451
      Época: 9
    - Pérdida: 0.2081
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: ReLU
      capas_ocultas:
      - 784
      - 392
      - 128
      - 64
      - 32
    performance: 2.6999576333333333
  timestamp: 24-12-20_814452
- resultado:
    accuracy: 96.17
    df:
    - Pérdida: 0.3397
      Época: 1
    - Pérdida: 0.0842
      Época: 2
    - Pérdida: 0.0736
      Época: 3
    - Pérdida: 0.1327
      Época: 4
    - Pérdida: 0.1231
      Época: 5
    - Pérdida: 0.2451
      Época: 6
    - Pérdida: 0.3511
      Época: 7
    - Pérdida: 0.1892
      Época: 8
    - Pérdida: 0.3534
      Época: 9
    - Pérdida: 0.2176
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Tanh
      capas_ocultas:
      - 784
      - 512
      - 256
    performance: 2.5726426833333336
  timestamp: 24-12-20_265172
- resultado:
    accuracy: 95.86
    df:
    - Pérdida: 0.279
      Época: 1
    - Pérdida: 0.257
      Época: 2
    - Pérdida: 0.6049
      Época: 3
    - Pérdida: 0.1077
      Época: 4
    - Pérdida: 0.1488
      Época: 5
    - Pérdida: 0.421
      Época: 6
    - Pérdida: 0.1103
      Época: 7
    - Pérdida: 0.0857
      Época: 8
    - Pérdida: 0.228
      Época: 9
    - Pérdida: 0.2311
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Tanh
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.6862337666666667
  timestamp: 24-12-20_470814
- resultado:
    accuracy: 96.71
    df:
    - Pérdida: 0.2255
      Época: 1
    - Pérdida: 0.103
      Época: 2
    - Pérdida: 0.0742
      Época: 3
    - Pérdida: 0.1223
      Época: 4
    - Pérdida: 0.0359
      Época: 5
    - Pérdida: 0.2045
      Época: 6
    - Pérdida: 0.0557
      Época: 7
    - Pérdida: 0.1147
      Época: 8
    - Pérdida: 0.0427
      Época: 9
    - Pérdida: 0.0578
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Tanh
      capas_ocultas:
      - 784
      - 392
    performance: 2.3580221833333335
  timestamp: 24-12-20_928833
- resultado:
    accuracy: 95.29
    df:
    - Pérdida: 0.3577
      Época: 1
    - Pérdida: 0.4027
      Época: 2
    - Pérdida: 0.196
      Época: 3
    - Pérdida: 0.1871
      Época: 4
    - Pérdida: 0.0645
      Época: 5
    - Pérdida: 0.5066
      Época: 6
    - Pérdida: 0.1499
      Época: 7
    - Pérdida: 0.135
      Época: 8
    - Pérdida: 0.5996
      Época: 9
    - Pérdida: 0.0872
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Tanh
      capas_ocultas:
      - 784
      - 392
      - 128
      - 64
      - 32
    performance: 2.4887745333333333
  timestamp: 24-12-20_305177
- resultado:
    accuracy: 97.7
    df:
    - Pérdida: 0.4967
      Época: 1
    - Pérdida: 0.1509
      Época: 2
    - Pérdida: 0.3011
      Época: 3
    - Pérdida: 0.0511
      Época: 4
    - Pérdida: 0.0449
      Época: 5
    - Pérdida: 0.0378
      Época: 6
    - Pérdida: 0.0329
      Época: 7
    - Pérdida: 0.0784
      Época: 8
    - Pérdida: 0.1258
      Época: 9
    - Pérdida: 0.2175
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
    performance: 2.7194583833333335
  timestamp: 24-12-20_825319
- resultado:
    accuracy: 97.97
    df:
    - Pérdida: 0.1709
      Época: 1
    - Pérdida: 0.1888
      Época: 2
    - Pérdida: 0.1096
      Época: 3
    - Pérdida: 0.0627
      Época: 4
    - Pérdida: 0.0963
      Época: 5
    - Pérdida: 0.0402
      Época: 6
    - Pérdida: 0.0179
      Época: 7
    - Pérdida: 0.0109
      Época: 8
    - Pérdida: 0.1166
      Época: 9
    - Pérdida: 0.0045
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.7574750166666666
  timestamp: 24-12-20_647355
- resultado:
    accuracy: 97.83
    df:
    - Pérdida: 0.2098
      Época: 1
    - Pérdida: 0.1792
      Época: 2
    - Pérdida: 0.3117
      Época: 3
    - Pérdida: 0.2081
      Época: 4
    - Pérdida: 0.0106
      Época: 5
    - Pérdida: 0.011
      Época: 6
    - Pérdida: 0.0922
      Época: 7
    - Pérdida: 0.01
      Época: 8
    - Pérdida: 0.1106
      Época: 9
    - Pérdida: 0.1459
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 392
    performance: 2.3852240666666664
  timestamp: 24-12-20_032359
- resultado:
    accuracy: 97.93
    df:
    - Pérdida: 0.2641
      Época: 1
    - Pérdida: 0.0909
      Época: 2
    - Pérdida: 0.1287
      Época: 3
    - Pérdida: 0.1693
      Época: 4
    - Pérdida: 0.0635
      Época: 5
    - Pérdida: 0.1979
      Época: 6
    - Pérdida: 0.1266
      Época: 7
    - Pérdida: 0.0276
      Época: 8
    - Pérdida: 0.0908
      Época: 9
    - Pérdida: 0.0914
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 392
      - 128
      - 64
      - 32
    performance: 2.4913912666666667
  timestamp: 24-12-20_661083
- resultado:
    accuracy: 97.58
    df:
    - Pérdida: 0.5378
      Época: 1
    - Pérdida: 0.2559
      Época: 2
    - Pérdida: 0.0203
      Época: 3
    - Pérdida: 0.2774
      Época: 4
    - Pérdida: 0.0112
      Época: 5
    - Pérdida: 0.0789
      Época: 6
    - Pérdida: 0.0236
      Época: 7
    - Pérdida: 0.2198
      Época: 8
    - Pérdida: 0.0075
      Época: 9
    - Pérdida: 0.0341
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Sigmoid
      capas_ocultas:
      - 784
      - 512
      - 256
    performance: 2.5444346166666665
  timestamp: 24-12-20_580287
- resultado:
    accuracy: 97.55
    df:
    - Pérdida: 0.6073
      Época: 1
    - Pérdida: 0.2634
      Época: 2
    - Pérdida: 0.0383
      Época: 3
    - Pérdida: 0.1713
      Época: 4
    - Pérdida: 0.1035
      Época: 5
    - Pérdida: 0.1668
      Época: 6
    - Pérdida: 0.0714
      Época: 7
    - Pérdida: 0.0892
      Época: 8
    - Pérdida: 0.0888
      Época: 9
    - Pérdida: 0.0045
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Sigmoid
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.749217633333333
  timestamp: 24-12-20_768066
- resultado:
    accuracy: 97.74
    df:
    - Pérdida: 0.3037
      Época: 1
    - Pérdida: 0.1211
      Época: 2
    - Pérdida: 0.0358
      Época: 3
    - Pérdida: 0.1452
      Época: 4
    - Pérdida: 0.0198
      Época: 5
    - Pérdida: 0.0231
      Época: 6
    - Pérdida: 0.0229
      Época: 7
    - Pérdida: 0.1048
      Época: 8
    - Pérdida: 0.0081
      Época: 9
    - Pérdida: 0.1558
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Sigmoid
      capas_ocultas:
      - 784
      - 392
    performance: 2.3423625333333336
  timestamp: 24-12-20_314861
- resultado:
    accuracy: 96.96
    df:
    - Pérdida: 1.0358
      Época: 1
    - Pérdida: 0.646
      Época: 2
    - Pérdida: 0.2161
      Época: 3
    - Pérdida: 0.1075
      Época: 4
    - Pérdida: 0.2204
      Época: 5
    - Pérdida: 0.0537
      Época: 6
    - Pérdida: 0.2724
      Época: 7
    - Pérdida: 0.2287
      Época: 8
    - Pérdida: 0.0845
      Época: 9
    - Pérdida: 0.0464
      Época: 10
    hiperparametros:
      batch_size: 64
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Sigmoid
      capas_ocultas:
      - 784
      - 392
      - 128
      - 64
      - 32
    performance: 2.4552523833333333
  timestamp: 24-12-20_936662
