- resultado:
    accuracy: 10.28
    df:
    - Pérdida: 2.0211
      Época: 1
    - Pérdida: 2.1441
      Época: 2
    - Pérdida: 1.6523
      Época: 3
    - Pérdida: 2.2475
      Época: 4
    - Pérdida: 2.263
      Época: 5
    - Pérdida: 2.328
      Época: 6
    - Pérdida: 2.3111
      Época: 7
    - Pérdida: 2.3044
      Época: 8
    - Pérdida: 2.3619
      Época: 9
    - Pérdida: 2.3343
      Época: 10
    - Pérdida: 2.2815
      Época: 11
    - Pérdida: 2.3168
      Época: 12
    - Pérdida: 2.3107
      Época: 13
    - Pérdida: 2.3062
      Época: 14
    - Pérdida: 2.309
      Época: 15
    hiperparametros:
      batch_size: 16
      epochs: 15
      learning_rate: 0.01
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 7.522289216666667
  timestamp: 24-12-20_275493
- resultado:
    accuracy: 95.22
    df:
    - Pérdida: 2.0451
      Época: 1
    - Pérdida: 1.3566
      Época: 2
    - Pérdida: 0.3671
      Época: 3
    - Pérdida: 0.3353
      Época: 4
    - Pérdida: 0.5477
      Época: 5
    - Pérdida: 0.5753
      Época: 6
    - Pérdida: 0.3026
      Época: 7
    - Pérdida: 0.2862
      Época: 8
    - Pérdida: 0.2265
      Época: 9
    - Pérdida: 0.3834
      Época: 10
    - Pérdida: 0.3252
      Época: 11
    - Pérdida: 0.2088
      Época: 12
    - Pérdida: 0.2493
      Época: 13
    - Pérdida: 0.4175
      Época: 14
    - Pérdida: 0.055
      Época: 15
    hiperparametros:
      batch_size: 16
      epochs: 15
      learning_rate: 0.01
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.891589316666667
  timestamp: 24-12-20_885133
- resultado:
    accuracy: 11.35
    df:
    - Pérdida: 1.9207
      Época: 1
    - Pérdida: 2.2635
      Época: 2
    - Pérdida: 2.3293
      Época: 3
    - Pérdida: 2.3121
      Época: 4
    - Pérdida: 2.2926
      Época: 5
    - Pérdida: 2.2956
      Época: 6
    - Pérdida: 2.2935
      Época: 7
    - Pérdida: 2.3126
      Época: 8
    - Pérdida: 2.3011
      Época: 9
    - Pérdida: 2.2696
      Época: 10
    hiperparametros:
      batch_size: 16
      epochs: 10
      learning_rate: 0.01
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.8457865
  timestamp: 24-12-20_977693
- resultado:
    accuracy: 94.22
    df:
    - Pérdida: 1.9087
      Época: 1
    - Pérdida: 0.4465
      Época: 2
    - Pérdida: 0.2764
      Época: 3
    - Pérdida: 0.3908
      Época: 4
    - Pérdida: 0.8855
      Época: 5
    - Pérdida: 0.8141
      Época: 6
    - Pérdida: 0.0917
      Época: 7
    - Pérdida: 0.2954
      Época: 8
    - Pérdida: 0.1299
      Época: 9
    - Pérdida: 0.0963
      Época: 10
    hiperparametros:
      batch_size: 16
      epochs: 10
      learning_rate: 0.01
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 3.625666916666667
  timestamp: 24-12-20_740247
- resultado:
    accuracy: 96.9
    df:
    - Pérdida: 0.086
      Época: 1
    - Pérdida: 0.2457
      Época: 2
    - Pérdida: 0.1391
      Época: 3
    - Pérdida: 0.3941
      Época: 4
    - Pérdida: 0.1106
      Época: 5
    - Pérdida: 0.0539
      Época: 6
    - Pérdida: 0.1334
      Época: 7
    - Pérdida: 0.1182
      Época: 8
    - Pérdida: 0.1157
      Época: 9
    - Pérdida: 0.1062
      Época: 10
    - Pérdida: 0.0203
      Época: 11
    - Pérdida: 0.0998
      Época: 12
    - Pérdida: 0.0402
      Época: 13
    - Pérdida: 0.0258
      Época: 14
    - Pérdida: 0.0286
      Época: 15
    hiperparametros:
      batch_size: 16
      epochs: 15
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 7.518878833333333
  timestamp: 24-12-20_066813
- resultado:
    accuracy: 79.1
    df:
    - Pérdida: 2.2629
      Época: 1
    - Pérdida: 2.3401
      Época: 2
    - Pérdida: 2.3312
      Época: 3
    - Pérdida: 2.2287
      Época: 4
    - Pérdida: 2.3252
      Época: 5
    - Pérdida: 2.2456
      Época: 6
    - Pérdida: 2.2578
      Época: 7
    - Pérdida: 2.1398
      Época: 8
    - Pérdida: 1.4762
      Época: 9
    - Pérdida: 1.3726
      Época: 10
    - Pérdida: 1.1999
      Época: 11
    - Pérdida: 0.8748
      Época: 12
    - Pérdida: 0.6971
      Época: 13
    - Pérdida: 1.2369
      Época: 14
    - Pérdida: 0.6654
      Época: 15
    hiperparametros:
      batch_size: 16
      epochs: 15
      learning_rate: 0.001
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.996444033333333
  timestamp: 24-12-20_941688
- resultado:
    accuracy: 97.2
    df:
    - Pérdida: 0.2662
      Época: 1
    - Pérdida: 0.0407
      Época: 2
    - Pérdida: 0.0632
      Época: 3
    - Pérdida: 0.0504
      Época: 4
    - Pérdida: 0.0635
      Época: 5
    - Pérdida: 0.0345
      Época: 6
    - Pérdida: 0.0098
      Época: 7
    - Pérdida: 0.0724
      Época: 8
    - Pérdida: 0.0652
      Época: 9
    - Pérdida: 0.3744
      Época: 10
    hiperparametros:
      batch_size: 16
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.959642633333333
  timestamp: 24-12-20_863071
- resultado:
    accuracy: 40.75
    df:
    - Pérdida: 2.3483
      Época: 1
    - Pérdida: 2.2585
      Época: 2
    - Pérdida: 2.3063
      Época: 3
    - Pérdida: 2.3128
      Época: 4
    - Pérdida: 2.2941
      Época: 5
    - Pérdida: 2.2931
      Época: 6
    - Pérdida: 2.2473
      Época: 7
    - Pérdida: 2.279
      Época: 8
    - Pérdida: 1.8558
      Época: 9
    - Pérdida: 1.6242
      Época: 10
    hiperparametros:
      batch_size: 16
      epochs: 10
      learning_rate: 0.001
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 3.5087269
  timestamp: 24-12-20_747777
- resultado:
    accuracy: 10.1
    df:
    - Pérdida: 2.3108
      Época: 1
    - Pérdida: 2.3191
      Época: 2
    - Pérdida: 2.3201
      Época: 3
    - Pérdida: 2.2861
      Época: 4
    - Pérdida: 2.3118
      Época: 5
    - Pérdida: 2.2844
      Época: 6
    - Pérdida: 2.2896
      Época: 7
    - Pérdida: 2.2938
      Época: 8
    - Pérdida: 2.3153
      Época: 9
    - Pérdida: 2.3094
      Época: 10
    - Pérdida: 2.3012
      Época: 11
    - Pérdida: 2.3132
      Época: 12
    - Pérdida: 2.3036
      Época: 13
    - Pérdida: 2.3233
      Época: 14
    - Pérdida: 2.3144
      Época: 15
    hiperparametros:
      batch_size: 32
      epochs: 15
      learning_rate: 0.01
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 5.3238791333333335
  timestamp: 24-12-20_321879
- resultado:
    accuracy: 93.33
    df:
    - Pérdida: 2.3057
      Época: 1
    - Pérdida: 1.6226
      Época: 2
    - Pérdida: 1.0685
      Época: 3
    - Pérdida: 0.4277
      Época: 4
    - Pérdida: 0.3738
      Época: 5
    - Pérdida: 0.6398
      Época: 6
    - Pérdida: 0.3951
      Época: 7
    - Pérdida: 0.4913
      Época: 8
    - Pérdida: 0.6183
      Época: 9
    - Pérdida: 0.1498
      Época: 10
    - Pérdida: 0.1146
      Época: 11
    - Pérdida: 0.5234
      Época: 12
    - Pérdida: 0.3581
      Época: 13
    - Pérdida: 0.5594
      Época: 14
    - Pérdida: 0.2514
      Época: 15
    hiperparametros:
      batch_size: 32
      epochs: 15
      learning_rate: 0.01
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.093608
  timestamp: 24-12-20_981933
- resultado:
    accuracy: 11.35
    df:
    - Pérdida: 2.2965
      Época: 1
    - Pérdida: 2.2905
      Época: 2
    - Pérdida: 2.3068
      Época: 3
    - Pérdida: 2.306
      Época: 4
    - Pérdida: 2.2997
      Época: 5
    - Pérdida: 2.3232
      Época: 6
    - Pérdida: 2.3065
      Época: 7
    - Pérdida: 2.3004
      Época: 8
    - Pérdida: 2.3084
      Época: 9
    - Pérdida: 2.3108
      Época: 10
    hiperparametros:
      batch_size: 32
      epochs: 10
      learning_rate: 0.01
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 3.431568583333333
  timestamp: 24-12-20_893299
- resultado:
    accuracy: 91.41
    df:
    - Pérdida: 2.3189
      Época: 1
    - Pérdida: 1.3224
      Época: 2
    - Pérdida: 0.6685
      Época: 3
    - Pérdida: 0.4787
      Época: 4
    - Pérdida: 0.4752
      Época: 5
    - Pérdida: 0.3227
      Época: 6
    - Pérdida: 0.2332
      Época: 7
    - Pérdida: 0.4721
      Época: 8
    - Pérdida: 0.591
      Época: 9
    - Pérdida: 0.2356
      Época: 10
    hiperparametros:
      batch_size: 32
      epochs: 10
      learning_rate: 0.01
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.676437716666667
  timestamp: 24-12-20_427520
- resultado:
    accuracy: 97.55
    df:
    - Pérdida: 0.2046
      Época: 1
    - Pérdida: 0.2684
      Época: 2
    - Pérdida: 0.1748
      Época: 3
    - Pérdida: 0.0126
      Época: 4
    - Pérdida: 0.0458
      Época: 5
    - Pérdida: 0.0164
      Época: 6
    - Pérdida: 0.1379
      Época: 7
    - Pérdida: 0.0624
      Época: 8
    - Pérdida: 0.0302
      Época: 9
    - Pérdida: 0.2042
      Época: 10
    - Pérdida: 0.0958
      Época: 11
    - Pérdida: 0.019
      Época: 12
    - Pérdida: 0.0969
      Época: 13
    - Pérdida: 0.0551
      Época: 14
    - Pérdida: 0.1299
      Época: 15
    hiperparametros:
      batch_size: 32
      epochs: 15
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 6.040992483333333
  timestamp: 24-12-20_148737
- resultado:
    accuracy: 16.55
    df:
    - Pérdida: 2.3659
      Época: 1
    - Pérdida: 2.2485
      Época: 2
    - Pérdida: 2.3456
      Época: 3
    - Pérdida: 2.3655
      Época: 4
    - Pérdida: 2.2551
      Época: 5
    - Pérdida: 2.305
      Época: 6
    - Pérdida: 2.2922
      Época: 7
    - Pérdida: 2.2914
      Época: 8
    - Pérdida: 2.2914
      Época: 9
    - Pérdida: 2.2643
      Época: 10
    - Pérdida: 2.3298
      Época: 11
    - Pérdida: 2.2628
      Época: 12
    - Pérdida: 2.2793
      Época: 13
    - Pérdida: 2.2937
      Época: 14
    - Pérdida: 2.2801
      Época: 15
    hiperparametros:
      batch_size: 32
      epochs: 15
      learning_rate: 0.001
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 4.16348535
  timestamp: 24-12-20_953021
- resultado:
    accuracy: 97.11
    df:
    - Pérdida: 0.0576
      Época: 1
    - Pérdida: 0.6268
      Época: 2
    - Pérdida: 0.2197
      Época: 3
    - Pérdida: 0.026
      Época: 4
    - Pérdida: 0.1652
      Época: 5
    - Pérdida: 0.0644
      Época: 6
    - Pérdida: 0.0527
      Época: 7
    - Pérdida: 0.2329
      Época: 8
    - Pérdida: 0.0471
      Época: 9
    - Pérdida: 0.2653
      Época: 10
    hiperparametros:
      batch_size: 32
      epochs: 10
      learning_rate: 0.001
      optimizer_str: Adam
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 3.393025966666667
  timestamp: 24-12-20_577788
- resultado:
    accuracy: 15.96
    df:
    - Pérdida: 2.3219
      Época: 1
    - Pérdida: 2.3277
      Época: 2
    - Pérdida: 2.3147
      Época: 3
    - Pérdida: 2.3641
      Época: 4
    - Pérdida: 2.3221
      Época: 5
    - Pérdida: 2.3399
      Época: 6
    - Pérdida: 2.3811
      Época: 7
    - Pérdida: 2.2768
      Época: 8
    - Pérdida: 2.3135
      Época: 9
    - Pérdida: 2.2985
      Época: 10
    hiperparametros:
      batch_size: 32
      epochs: 10
      learning_rate: 0.001
      optimizer_str: SGD
    parametros:
      activation_fn: Softplus
      capas_ocultas:
      - 784
      - 512
      - 256
      - 128
    performance: 2.6293442666666667
  timestamp: 24-12-20_321248
