- resultado:
    accuracy: 0.9901
    hiperparametros:
      learning_rate: 0.003918194347141745
      num_epochs: 10
      optimizer_str: Adam
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 8.827556316666666
  timestamp: 24-12-20_309896
- resultado:
    accuracy: 0.987
    hiperparametros:
      learning_rate: 0.00362561763457623
      num_epochs: 10
      optimizer_str: RMSprop
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 8.565537683333334
  timestamp: 24-12-20_106180
- resultado:
    accuracy: 0.9934
    hiperparametros:
      learning_rate: 0.0007792297153882995
      num_epochs: 10
      optimizer_str: Adam
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.110359749999999
  timestamp: 24-12-20_057230
- resultado:
    accuracy: 0.908
    hiperparametros:
      learning_rate: 0.0008288916866885144
      num_epochs: 10
      optimizer_str: SGD
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.439160883333333
  timestamp: 24-12-20_073536
- resultado:
    accuracy: 0.991
    hiperparametros:
      learning_rate: 0.0001930783753654713
      num_epochs: 10
      optimizer_str: RMSprop
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.663069283333334
  timestamp: 24-12-20_452629
- resultado:
    accuracy: 0.9899
    hiperparametros:
      learning_rate: 0.00012966511753760403
      num_epochs: 10
      optimizer_str: RMSprop
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.65646005
  timestamp: 24-12-20_465409
- resultado:
    accuracy: 0.9862
    hiperparametros:
      learning_rate: 0.007535384509295551
      num_epochs: 10
      optimizer_str: Adam
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.491355283333332
  timestamp: 24-12-20_298794
- resultado:
    accuracy: 0.984
    hiperparametros:
      learning_rate: 0.009647685075720105
      num_epochs: 10
      optimizer_str: RMSprop
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.288436383333334
  timestamp: 24-12-20_595150
- resultado:
    accuracy: 0.9927
    hiperparametros:
      learning_rate: 0.0016722697006183672
      num_epochs: 10
      optimizer_str: Adam
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.555318666666667
  timestamp: 24-12-20_333126
- resultado:
    accuracy: 0.9908
    hiperparametros:
      learning_rate: 0.00011120513715710631
      num_epochs: 10
      optimizer_str: RMSprop
    parametros:
      dropout: 0.2900998503939086
      filters_l1: 34
      filters_l2: 115
      final_layer_size: 146
    performance: 9.47434265
  timestamp: 24-12-20_384079
