hiperparametros_1:
  batch_size: 16
  learning_rate: 0.01
  epochs: 15
  optimizer_str: Adam
hiperparametros_2:
  batch_size: 16
  learning_rate: 0.01
  epochs: 15
  optimizer_str: SGD
hiperparametros_3:
  batch_size: 16
  learning_rate: 0.01
  epochs: 10
  optimizer_str: Adam
hiperparametros_4:
  batch_size: 16
  learning_rate: 0.01
  epochs: 10
  optimizer_str: SGD
hiperparametros_5:
  batch_size: 16
  learning_rate: 0.001
  epochs: 15
  optimizer_str: Adam
hiperparametros_6:
  batch_size: 16
  learning_rate: 0.001
  epochs: 15
  optimizer_str: SGD
hiperparametros_7:
  batch_size: 16
  learning_rate: 0.001
  epochs: 10
  optimizer_str: Adam
hiperparametros_8:
  batch_size: 16
  learning_rate: 0.001
  epochs: 10
  optimizer_str: SGD
hiperparametros_9:
  batch_size: 32
  learning_rate: 0.01
  epochs: 15
  optimizer_str: Adam
hiperparametros_10:
  batch_size: 32
  learning_rate: 0.01
  epochs: 15
  optimizer_str: SGD
hiperparametros_11:
  batch_size: 32
  learning_rate: 0.01
  epochs: 10
  optimizer_str: Adam
hiperparametros_12:
  batch_size: 32
  learning_rate: 0.01
  epochs: 10
  optimizer_str: SGD
hiperparametros_13:
  batch_size: 32
  learning_rate: 0.001
  epochs: 15
  optimizer_str: Adam
hiperparametros_14:
  batch_size: 32
  learning_rate: 0.001
  epochs: 15
  optimizer_str: SGD
hiperparametros_15:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  optimizer_str: Adam
hiperparametros_16:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  optimizer_str: SGD
