hiperparametros_1:
    batch_size: 64
    epochs: 10
    learning_rate: 0.001
    optimizer_str: Adam

hiperparametros_2:
    batch_size: 128
    epochs: 20
    learning_rate: 0.0001
    optimizer_str: RMSprop

hiperparametros_3:
    batch_size: 32
    epochs: 25
    learning_rate: 0.01
    optimizer_str: RMSprop

hiperparametros_4:
    batch_size: 256
    epochs: 15
    learning_rate: 0.001
    optimizer_str: RMSprop